required = ["github.com/russross/blackfriday"]

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.12.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[prune]
  go-tests = true
  unused-packages = true
